apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>App 1</title>
      </head>
      <body>
        <h1>Welcome to App 1</h1>
        <p>This is the first application in the cluster.</p>
      </body>
    </html>
