# Vagrantfile for setting up a 3-node K3s Kubernetes cluster (1 master, 2 workers)
Vagrant.configure("2") do |config|
    # Define a common base configuration for all VMs
    config.vm.box = "ubuntu/focal64"  # Ubuntu 20.04
  
    # Define the master node
    config.vm.define "vbaronS" do |master|
      master.vm.hostname = "vbaronS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.network "forwarded_port", guest: 30080, host: 30080
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      master.vm.provision "shell", path: "scripts/vbaronS.sh"
    end
    config.vm.synced_folder "./confs", "/home/vagrant/confs"
  end